export const ENDPOINTS = {
  auth: {
    login: '/auth/login',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
  },
  monitoring: {
    autonomy: '/monitoring/autonomy',
    llmCost: '/monitoring/llm-cost',
    lifecycle: '/monitoring/conversation-lifecycle',
    rateLimits: '/monitoring/rate-limits',
    convergenceHistory: '/monitoring/convergence-history',
    pipelineTraces: '/monitoring/pipeline-traces',
    pipelineTraceDetail: (msgId: string) => `/monitoring/pipeline-traces/${msgId}`,
    pipelineHealth: '/monitoring/pipeline-health',
    injection: '/monitoring/injection',
    analyticsIocTimeline: '/monitoring/analytics/ioc-timeline',
    analyticsConversationTimeline: '/monitoring/analytics/conversation-timeline',
    analyticsIocDistribution: '/monitoring/analytics/ioc-distribution',
    analyticsScamDistribution: '/monitoring/analytics/scam-distribution',
    analyticsCostTimeline: '/monitoring/analytics/cost-timeline',
    analyticsPipelineTimeline: '/monitoring/analytics/pipeline-timeline',
    analyticsActivityFeed: '/monitoring/analytics/activity-feed',
    analyticsWeeklyTrends: '/monitoring/analytics/weekly-trends',
  },
  conversations: {
    list: '/communication/conversation',
    detail: (id: string) => `/communication/conversation/${id}`,
    messages: (id: string) => `/communication/conversation/${id}/messages`,
    iocs: (id: string) => `/communication/conversation/${id}/iocs`,
  },
  iocs: {
    list: '/iocs',
  },
  scambaiting: {
    stats: '/scambaiting/stats',
    statsByType: (code: string) => `/scambaiting/stats/${code}`,
    personaPerformance: (code: string) => `/scambaiting/persona/${code}/performance`,
    selectPersona: '/scambaiting/select-persona',
    closeConversation: (id: string) => `/scambaiting/conversation/${id}/close`,
  },
  campaign: {
    hunt: '/campaign/hunt',
    candidates: '/campaign/candidates',
    detail: (id: string) => `/campaign/${id}/detail`,
    profile: (id: string) => `/campaign/${id}/profile`,
    messages: (id: string) => `/campaign/${id}/messages`,
    exportStix: (id: string) => `/campaign/${id}/export/stix`,
    promoteRule: (ruleId: string) => `/campaign/rule/${ruleId}/promote`,
  },
  scamTypes: '/communication/scam-types',
  meta: {
    config: '/meta/config',
  },
} as const;
