export const ENDPOINTS = {
  auth: {
    login: '/auth/login',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
  },
  monitoring: {
    autonomy: '/monitoring/autonomy',
    llmCost: '/monitoring/llm-cost',
    lifecycle: '/monitoring/conversation-lifecycle',
    rateLimits: '/monitoring/rate-limits',
    convergenceHistory: '/monitoring/convergence-history',
    pipelineTraces: '/monitoring/pipeline-traces',
    pipelineTraceDetail: (msgId: string) => `/monitoring/pipeline-traces/${msgId}`,
    pipelineHealth: '/monitoring/pipeline-health',
    injection: '/monitoring/injection',
    analyticsIocTimeline: '/monitoring/analytics/ioc-timeline',
    analyticsConversationTimeline: '/monitoring/analytics/conversation-timeline',
    analyticsIocDistribution: '/monitoring/analytics/ioc-distribution',
    analyticsScamDistribution: '/monitoring/analytics/scam-distribution',
    analyticsCostTimeline: '/monitoring/analytics/cost-timeline',
    analyticsPipelineTimeline: '/monitoring/analytics/pipeline-timeline',
    analyticsActivityFeed: '/monitoring/analytics/activity-feed',
    analyticsWeeklyTrends: '/monitoring/analytics/weekly-trends',
    analyticsScammerEngagement: '/monitoring/analytics/scammer-engagement',
  },
  conversations: {
    list: '/communication/conversation',
    detail: (id: string) => `/communication/conversation/${id}`,
    messages: (id: string) => `/communication/conversation/${id}/messages`,
    iocs: (id: string) => `/communication/conversation/${id}/iocs`,
    // Live Bait Theater composite endpoint
    theater: (id: string) => `/communication/conversation/${id}/theater`,
    exportStix: (id: string) => `/conversations/${id}/export/stix`,
  },
  mailAccounts: {
    list: '/communication/mail-accounts',
  },
  iocs: {
    list: '/iocs',
    detail: (indicatorId: string) => `/iocs/${indicatorId}/detail`,
    coOccurrence: '/iocs/co-occurrence',
    context: (indicatorId: string) => `/iocs/${indicatorId}/context`,
    exportStix: '/iocs/export/stix',
    feedback: (indicatorId: string) => `/iocs/${indicatorId}/feedback`,
  },
  scambaiting: {
    stats: '/scambaiting/stats',
    statsByType: (code: string) => `/scambaiting/stats/${code}`,
    personaPerformance: (code: string) => `/scambaiting/persona/${code}/performance`,
    personaMatrix: '/scambaiting/persona-matrix',
    personaMirrors: (code: string) => `/personas/${code}/mirrors`,
    scamTypeMirrors: (code: string) => `/scam-types/${code}/mirrors`,
    selectPersona: '/scambaiting/select-persona',
    closeConversation: (id: string) => `/scambaiting/conversation/${id}/close`,
    reopenConversation: (id: string) => `/scambaiting/conversation/${id}/reopen`,
  },
  campaign: {
    hunt: '/campaign/hunt',
    candidates: '/campaign/candidates',
    detail: (id: string) => `/campaign/${id}/detail`,
    profile: (id: string) => `/campaign/${id}/profile`,
    messages: (id: string) => `/campaign/${id}/messages`,
    exportStix: (id: string) => `/campaign/${id}/export/stix`,
    promoteRule: (ruleId: string) => `/campaign/rule/${ruleId}/promote`,
  },
  personas: {
    create: '/personas',
    detail: (code: string) => `/personas/${code}`,
    update: (code: string) => `/personas/${code}`,
    toggleActive: (code: string) => `/personas/${code}/active`,
  },
  promptOverrides: {
    list: '/prompt-overrides',
    detail: (key: string) => `/prompt-overrides/${key}`,
    upsert: (key: string) => `/prompt-overrides/${key}`,
    remove: (key: string) => `/prompt-overrides/${key}`,
    canary: (key: string) => `/prompt-overrides/${key}/canary`,
    canaryJob: (jobId: number) => `/prompt-overrides/canary/${jobId}`,
    canaryLatest: (key: string) => `/prompt-overrides/${key}/canary/latest`,
  },
  clusters: {
    list: '/clusters',
    stats: '/clusters/stats',
    detail: (id: string) => `/clusters/${id}`,
    exportStix: (id: string) => `/clusters/${id}/export/stix`,
    forIoc: (indicatorId: string) => `/iocs/${indicatorId}/cluster`,
    psychProfile: (id: string) => `/clusters/${id}/psych-profile`,
    temporal: (id: string) => `/clusters/${id}/temporal`,
    abuseReport: (id: string) => `/clusters/${id}/abuse-report`,
  },
  ttps: {
    list: '/ttps',
    clusterMatrix: '/ttps/cluster-matrix',
    phaseTrend: '/ttps/phase-trend',
    reviewQueue: '/ttps/review-queue',
    sequences: '/ttps/sequences',
    phaseTransitions: '/ttps/phase-transitions',
    personaMatrix: '/ttps/persona-matrix',
    stimulusMatrix: '/ttps/stimulus-matrix',
    forCluster: (id: string) => `/clusters/${id}/ttps`,
    forConversation: (id: string) => `/conversations/${id}/ttps`,
    forIoc: (indicatorId: string) => `/iocs/${indicatorId}/ttps`,
    iocsFor: (code: string) => `/ttps/${code}/iocs`,
    clustersFor: (code: string) => `/ttps/${code}/clusters`,
    conversationsFor: (code: string) => `/ttps/${code}/conversations`,
  },
  impact: {
    summary: '/impact/summary',
    iocUniqueness: '/impact/ioc-uniqueness',
  },
  scamTypes: '/communication/scam-types',
  meta: {
    config: '/meta/config',
  },
  // admin LLM kill switch toggle
  admin: {
    llmKillSwitch: '/admin/llm/killswitch',
  },
} as const;
