<?php

declare(strict_types=1);

namespace App\Application\Campaign;

use App\Domain\CampaignRadar\Campaign;
use App\Domain\CampaignRadar\CampaignRule;
use App\Infrastructure\Campaign\Doctrine\CampaignRepository;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Log\LoggerInterface;
use Symfony\Component\Uid\Uuid;

/**
 * Handler to compile MailGuard DSL rules from a campaign profile.
 *
 * Uses the YAML profile generated by ProfileCampaignHandler to generate
 * executable DSL rules and store them in campaign_rule.
 */
final readonly class CompileRulesHandler
{
    public function __construct(
        private EntityManagerInterface $em,
        private CampaignRepository $campaignRepository,
        private RuleCompiler $compiler,
        private LoggerInterface $logger
    ) {
    }

    /**
     * Compiles DSL rules for a campaign and stores them in the database.
     *
     * @param Uuid                                                  $campaignId ID de la campagne
     * @param array{pos: array<int, mixed>, neg: array<int, mixed>} $examples   Optional examples to refine rules
     *
     * @throws \RuntimeException Si la campagne n'existe pas ou n'a pas de profil
     *
     * @return array{rules_dsl: string, rules_count: int, attempts: int, rule_ids: array<string>}
     */
    public function handle(Uuid $campaignId, array $examples = ['pos' => [], 'neg' => []]): array
    {
        $startTime = microtime(true);

        $this->logger->info('Starting DSL rule compilation for campaign', [
            'campaign_id' => $campaignId->toRfc4122(),
            'examples_pos' => count($examples['pos']),
            'examples_neg' => count($examples['neg']),
        ]);

        // 1. Verify campaign exists
        $campaign = $this->campaignRepository->findById($campaignId);

        if (!$campaign instanceof \App\Domain\CampaignRadar\Campaign) {
            throw new \RuntimeException("Campaign not found: {$campaignId->toRfc4122()}");
        }

        // 2. Verify profile exists
        $profileYaml = $campaign->getProfileYaml();

        if ($profileYaml === null) {
            throw new \RuntimeException(
                "Campaign has no profile. Run profiling first for campaign: {$campaignId->toRfc4122()}"
            );
        }

        // 3. Compile DSL rules
        $result = $this->compiler->compile($profileYaml, $examples);

        // 4. Extract individual rules and store them
        $ruleIds = $this->storeRules($campaign, $result['rules_dsl']);

        $latencyMs = (int) ((microtime(true) - $startTime) * 1000);

        $this->logger->info('DSL rule compilation completed', [
            'campaign_id' => $campaignId->toRfc4122(),
            'rules_count' => $result['rules_count'],
            'attempts' => $result['attempts'],
            'latency_ms' => $latencyMs,
        ]);

        return [
            'rules_dsl' => $result['rules_dsl'],
            'rules_count' => $result['rules_count'],
            'attempts' => $result['attempts'],
            'rule_ids' => $ruleIds,
        ];
    }

    /**
     * Stores compiled DSL rules in campaign_rule.
     *
     * @param string $rulesDsl DSL text containing 1 to 3 rules
     *
     * @return array<string> IDs of created rules
     */
    private function storeRules(Campaign $campaign, string $rulesDsl): array
    {
        $ruleIds = [];

        // Parse individual rules (format: RULE name { ... })
        preg_match_all('/RULE\s+([\w.]+)\s*\{(.*?)\}/s', $rulesDsl, $matches, PREG_SET_ORDER);

        foreach ($matches as $match) {
            $ruleName = $match[1];
            $ruleBody = $match[0]; // Complete rule with RULE ... { ... }

            // Create CampaignRule entity
            $rule = new CampaignRule(
                $campaign->getCampaignId(),
                $ruleBody
            );

            $this->em->persist($rule);
            $ruleIds[] = $rule->getRuleId()->toRfc4122();

            $this->logger->debug('Created campaign rule', [
                'rule_id' => $rule->getRuleId()->toRfc4122(),
                'rule_name' => $ruleName,
                'campaign_id' => $campaign->getCampaignId()->toRfc4122(),
            ]);
        }

        $this->em->flush();

        return $ruleIds;
    }
}
