<?php

declare(strict_types=1);

namespace App\Application\Campaign;

use App\Domain\Communication\Message;

final class PromptBuilder
{
    /**
     * Builds prompts for campaign profiling.
     *
     * @param array<Message> $sampleMessages Campaign messages (3-10 max)
     *
     * @return array{system: string, user: string}
     */
    public function buildCampaignProfilerPrompts(array $sampleMessages): array
    {
        $systemPrompt = <<<'PROMPT'
You are a Threat Intelligence analyst specialized in phishing/scam campaigns.

From a sample of suspicious emails, you must:

1. **Describe** the campaign (tactics, targets, CTA, technical clues)
2. **Predict** likely variants (new subjects, display names, URL shapes)

⚠️ STRICT CONSTRAINTS:
- Output **strict YAML only**
- **NO PII** (no email addresses, no phone numbers in clear)
- Use "lookalike" for brands (e.g., "bank-lookalike", not "BNP Paribas")
- Focus on **reusable patterns**, not specific instances

Expected output format:

campaign:
  summary: "Short description (1 sentence)"
  tactics: ["tactic1", "tactic2"]
  target_audience: "who is targeted"
  cta: "primary call-to-action"
  risk: 1-5

variants:
  subjects: ["variant1", "variant2"]
  display_names: ["name1", "name2"]
  url_shapes: ["pattern1", "pattern2"]

infra:
  domain_age_pattern: "< Xd"
  dkim_spf_pattern: "absent|fail"
  mx_provider_pattern: "low-cost|generic"
PROMPT;

        $userPrompt = sprintf(
            "Here is a sample of %d suspicious emails grouped in a cluster:\n\n",
            count($sampleMessages)
        );

        foreach ($sampleMessages as $i => $message) {
            $bodyText = $message->getBodyText();
            $sanitizedBody = $this->maskEmailsInText($bodyText);
            $sanitizedBody = $this->defangUrlsInText($sanitizedBody);

            $userPrompt .= sprintf(
                "---\nMessage %d:\nSubject: %s\nFrom: %s\nBody (excerpt): %s\nURL(s): %s\nDKIM: %s\n---\n\n",
                $i + 1,
                $message->getSubject() ?: 'no subject',
                $this->maskEmail(\is_string($message->getHeaders()['from'] ?? null) ? $message->getHeaders()['from'] : 'unknown'),
                $this->truncateText($sanitizedBody, 200),
                implode(', ', $this->extractUrls($bodyText)),
                $this->getDkimStatus($message)
            );
        }

        $userPrompt .= "\nProfile this campaign and generate the output YAML.";

        return [
            'system' => $systemPrompt,
            'user' => $userPrompt,
        ];
    }

    /**
     * Builds prompts for DSL rule compilation.
     *
     * @param string                                                $profileYaml YAML profile generated by CampaignProfiler
     * @param array{pos: array<int, mixed>, neg: array<int, mixed>} $examples    Positive/negative examples
     *
     * @return array{system: string, user: string}
     */
    public function buildRuleCompilerPrompts(string $profileYaml, array $examples): array
    {
        $systemPrompt = <<<'PROMPT'
You are an expert in generating detection rules in the **MailGuard DSL** format.

From a YAML campaign profile, generate **1 to 3 DSL rules**.

⚠️ STRICT CONSTRAINTS:
- **Strict** DSL syntax: RULE { WHERE ... ACTION ... }
- **No PII**
- Allowed fields only: subject, body, url.domain.age, sender.display_name, dkim.pass, spf.pass
- Allowed operators: simhash≈, containsAny, fuzzy ∈, <, >, =, ∈
- **Pure DSL** output (no explanation, no markdown)

Expected output example:

RULE scam.bank_otp_2025_10 {
  WHERE subject.simhash≈"important notice" ±15%
    AND body.containsAny ["confirm identity","verify account"]
    AND url.domain.age < 14d
    AND dkim.pass ∈ {false, null}
  ACTION tag="campaign:bank_otp_2025_10", score+=40
}
PROMPT;

        $userPrompt = "Campaign YAML profile:\n\n" . $profileYaml . "\n\n---\n\n";

        if (!empty($examples['pos'])) {
            $userPrompt .= "Positive examples (must match):\n";

            foreach ($examples['pos'] as $ex) {
                /** @var array{subject?: string, body?: string, dkim?: string} $ex */
                $userPrompt .= sprintf(
                    "- Subject: %s, Body: %s, DKIM: %s\n",
                    $ex['subject'] ?? 'N/A',
                    $this->truncateText($ex['body'] ?? '', 50),
                    $ex['dkim'] ?? 'N/A'
                );
            }
            $userPrompt .= "\n";
        }

        if (!empty($examples['neg'])) {
            $userPrompt .= "Negative examples (must NOT match):\n";

            foreach ($examples['neg'] as $ex) {
                /** @var array{subject?: string, body?: string, dkim?: string} $ex */
                $userPrompt .= sprintf(
                    "- Subject: %s, Body: %s, DKIM: %s\n",
                    $ex['subject'] ?? 'N/A',
                    $this->truncateText($ex['body'] ?? '', 50),
                    $ex['dkim'] ?? 'N/A'
                );
            }
            $userPrompt .= "\n";
        }

        $userPrompt .= "---\n\nGenerate the MailGuard DSL rules.";

        return [
            'system' => $systemPrompt,
            'user' => $userPrompt,
        ];
    }

    // === Private Helpers ===

    /**
     * Truncates text to N characters.
     */
    private function truncateText(string $text, int $maxLength): string
    {
        if (mb_strlen($text) <= $maxLength) {
            return $text;
        }

        return mb_substr($text, 0, $maxLength) . '...';
    }

    /**
     * Masks an email address (GDPR).
     */
    private function maskEmail(string $email): string
    {
        if (preg_match('/^([^@]+)@(.+)$/', $email, $matches)) {
            $local = $matches[1];
            $domain = $matches[2];

            // Mask local part
            $maskedLocal = substr($local, 0, 2) . '***';

            return $maskedLocal . '@' . $domain;
        }

        return '***@***';
    }

    /**
     * Masks all email addresses in a text (GDPR).
     */
    private function maskEmailsInText(string $text): string
    {
        return preg_replace_callback(
            '/\b[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}\b/i',
            fn ($matches): string => $this->maskEmail($matches[0]),
            $text
        ) ?? $text;
    }

    /**
     * Defangs all URLs in a text (security).
     */
    private function defangUrlsInText(string $text): string
    {
        return str_replace(['http://', 'https://'], ['hxxp://', 'hxxps://'], $text);
    }

    /**
     * Extracts URLs from a text.
     *
     * @return array<string>
     */
    private function extractUrls(string $text): array
    {
        $pattern = '/https?:\/\/[^\s<>"]+/i';
        preg_match_all($pattern, $text, $matches);

        $urls = $matches[0];

        // Defang URLs
        return array_map(fn ($url): string => str_replace(['http://', 'https://'], ['hxxp://', 'hxxps://'], $url), $urls);
    }

    /**
     * Retrieves the DKIM status of a message.
     */
    private function getDkimStatus(Message $message): string
    {
        $headers = $message->getHeaders();
        /** @var array<string, mixed> $auth */
        $auth = $headers['auth'] ?? [];
        $dkim = $auth['dkim'] ?? null;

        if ($dkim === true) {
            return 'pass';
        }

        if ($dkim === false) {
            return 'fail';
        }

        return 'absent';
    }
}
