<?php

declare(strict_types=1);

namespace App\Application\Campaign;

use App\Application\LLM\Port\LLMClientInterface;
use Psr\Log\LoggerInterface;

/**
 * Rule Compiler - MailGuard DSL rule generation
 *
 * Compiles a campaign YAML profile into executable MailGuard DSL rules.
 *
 * Features:
 * - Retry logic with exponential backoff (1s, 2s, 4s)
 * - DSL syntax validation
 * - Automatic test generation
 * - Detailed logging
 */
final readonly class RuleCompiler
{
    private const MAX_RETRIES = 3;
    private const TIMEOUT_SEC = 45;

    /**
     * Exponential backoff delays (seconds).
     *
     * @var array<int>
     */
    private const BACKOFF_DELAYS = [1, 2, 4];

    /**
     * Allowed DSL syntax.
     */
    private const DSL_ALLOWED_FIELDS = [
        'subject',
        'body',
        'url.domain.age',
        'sender.display_name',
        'dkim.pass',
        'spf.pass',
    ];

    private const DSL_ALLOWED_OPERATORS = [
        'simhash≈',
        'containsAny',
        'fuzzy',
        '∈',
        '<',
        '>',
        '=',
    ];

    public function __construct(
        private LLMClientInterface $llmClient,
        private PromptBuilder $promptBuilder,
        private LoggerInterface $logger
    ) {
    }

    /**
     * Compiles a YAML profile into MailGuard DSL rules.
     *
     * @param string                                                $profileYaml YAML profile generated by CampaignProfiler
     * @param array{pos: array<int, mixed>, neg: array<int, mixed>} $examples    Positive/negative examples (optional)
     *
     * @throws \RuntimeException If compilation fails after MAX_RETRIES attempts
     *
     * @return array{rules_dsl: string, rules_count: int, attempts: int}
     */
    public function compile(string $profileYaml, array $examples = ['pos' => [], 'neg' => []]): array
    {
        $startTime = microtime(true);

        $this->logger->info('Starting DSL rule compilation', [
            'profile_length' => strlen($profileYaml),
            'examples_pos' => count($examples['pos']),
            'examples_neg' => count($examples['neg']),
        ]);

        $result = $this->compileWithRetry($profileYaml, $examples);

        $latencyMs = (int) ((microtime(true) - $startTime) * 1000);

        $this->logger->info('DSL rule compilation completed', [
            'rules_count' => $result['rules_count'],
            'attempts' => $result['attempts'],
            'latency_ms' => $latencyMs,
        ]);

        return $result;
    }

    /**
     * Compile with retry logic and exponential backoff.
     *
     * @param array{pos: array<int, mixed>, neg: array<int, mixed>} $examples
     *
     * @throws \RuntimeException If all attempts fail
     *
     * @return array{rules_dsl: string, rules_count: int, attempts: int}
     */
    private function compileWithRetry(string $profileYaml, array $examples): array
    {
        $lastException = null;

        for ($attempt = 1; $attempt <= self::MAX_RETRIES; $attempt++) {
            try {
                $this->logger->debug("Compilation attempt {$attempt}/" . self::MAX_RETRIES);

                // 1. Build the prompts
                $prompts = $this->promptBuilder->buildRuleCompilerPrompts($profileYaml, $examples);

                // 2. LLM call
                $messages = [
                    ['role' => 'system', 'content' => $prompts['system']],
                    ['role' => 'user', 'content' => $prompts['user']],
                ];

                $response = $this->llmClient->chat($messages, [
                    'temperature' => 0.2, // Very low temperature for strict syntax
                    'max_tokens' => 1000,
                    'timeout' => self::TIMEOUT_SEC,
                    'purpose' => 'rule_compilation',
                ]);

                // 3. Extract DSL from response (may contain markdown)
                $dslText = $this->extractDSL($response);

                // 4. Validate DSL syntax
                $this->validateDSL($dslText);

                // 5. Count rules
                $rulesCount = $this->countRules($dslText);

                $this->logger->info('DSL compilation succeeded', [
                    'attempt' => $attempt,
                    'rules_count' => $rulesCount,
                    'dsl_length' => strlen($dslText),
                ]);

                return [
                    'rules_dsl' => $dslText,
                    'rules_count' => $rulesCount,
                    'attempts' => $attempt,
                ];
            } catch (\Throwable $e) {
                $lastException = $e;

                $this->logger->warning("Compilation attempt {$attempt} failed", [
                    'attempt' => $attempt,
                    'error' => $e->getMessage(),
                ]);

                // If not the last attempt, wait with backoff
                if ($attempt < self::MAX_RETRIES) {
                    $delay = self::BACKOFF_DELAYS[$attempt - 1];
                    $this->logger->debug("Retrying in {$delay}s...");
                    sleep($delay);
                }
            }
        }

        // All attempts failed
        /** @var \Throwable $lastException */
        throw new \RuntimeException(
            'DSL compilation failed after ' . self::MAX_RETRIES . ' attempts: ' . $lastException->getMessage(),
            previous: $lastException
        );
    }

    /**
     * Extracts DSL from an LLM response (may contain markdown).
     */
    private function extractDSL(string $response): string
    {
        $response = trim($response);

        // Case 1: DSL inside a markdown code block
        if (preg_match('/```(?:dsl)?\s*(RULE\s+.*?)```/s', $response, $matches)) {
            return trim($matches[1]);
        }

        // Case 2: Raw DSL (starts with "RULE")
        if (preg_match('/(RULE\s+.*)/s', $response, $matches)) {
            return trim($matches[1]);
        }

        throw new \RuntimeException('No valid DSL found in LLM response');
    }

    /**
     * Validates the DSL syntax.
     *
     * @throws \RuntimeException If the syntax is invalid
     */
    private function validateDSL(string $dslText): void
    {
        // 1. Verify general structure RULE { WHERE ... ACTION ... }
        if (!preg_match('/RULE\s+[\w.]+\s*\{.*WHERE\s+.*ACTION\s+.*\}/s', $dslText)) {
            throw new \RuntimeException('Invalid DSL structure: expected RULE { WHERE ... ACTION ... }');
        }

        // 2. Extract all rules
        preg_match_all('/RULE\s+([\w.]+)\s*\{(.*?)\}/s', $dslText, $matches, PREG_SET_ORDER);

        if ($matches === []) {
            throw new \RuntimeException('No valid RULE blocks found');
        }

        foreach ($matches as $match) {
            $ruleName = $match[1];
            $ruleBody = $match[2];

            // 3. Verify WHERE clause presence
            if (!preg_match('/WHERE\s+/i', $ruleBody)) {
                throw new \RuntimeException("Missing WHERE clause in rule: {$ruleName}");
            }

            // 4. Verify ACTION clause presence
            if (!preg_match('/ACTION\s+/i', $ruleBody)) {
                throw new \RuntimeException("Missing ACTION clause in rule: {$ruleName}");
            }

            // 5. Extract used fields
            preg_match_all('/\b(' . implode('|', array_map('preg_quote', self::DSL_ALLOWED_FIELDS)) . ')\b/', $ruleBody, $fieldMatches);

            // 6. Verify at least one field is used
            if (empty($fieldMatches[0])) {
                throw new \RuntimeException("No valid fields found in rule: {$ruleName}");
            }

            // 7. Verify at least one operator is used
            $hasOperator = false;

            foreach (self::DSL_ALLOWED_OPERATORS as $op) {
                if (str_contains($ruleBody, $op)) {
                    $hasOperator = true;

                    break;
                }
            }

            if (!$hasOperator) {
                throw new \RuntimeException("No valid operators found in rule: {$ruleName}");
            }
        }

        $this->logger->debug('DSL validation passed', [
            'rules_count' => count($matches),
        ]);
    }

    /**
     * Counts the number of rules in the DSL.
     */
    private function countRules(string $dslText): int
    {
        preg_match_all('/RULE\s+[\w.]+\s*\{/i', $dslText, $matches);

        return count($matches[0]);
    }

    /**
     * Generates automatic tests for DSL rules.
     *
     * @param string                                                $rulesDsl Generated DSL rules
     * @param array{pos: array<int, mixed>, neg: array<int, mixed>} $examples Examples used for generation
     *
     * @return array{test_cases: array<int, array{description: string, input: array<string, mixed>, expected: bool}>}
     */
    public function generateTests(string $rulesDsl, array $examples): array
    {
        $testCases = [];

        // Positive tests (must match)
        foreach ($examples['pos'] as $i => $ex) {
            /** @var array<string, mixed> $ex */
            $testCases[] = [
                'description' => "Positive example {$i} should match",
                'input' => [
                    'subject' => $ex['subject'] ?? '',
                    'body' => $ex['body'] ?? '',
                    'dkim' => $ex['dkim'] ?? null,
                ],
                'expected' => true,
            ];
        }

        // Negative tests (must NOT match)
        foreach ($examples['neg'] as $i => $ex) {
            /** @var array<string, mixed> $ex */
            $testCases[] = [
                'description' => "Negative example {$i} should NOT match",
                'input' => [
                    'subject' => $ex['subject'] ?? '',
                    'body' => $ex['body'] ?? '',
                    'dkim' => $ex['dkim'] ?? null,
                ],
                'expected' => false,
            ];
        }

        $this->logger->info('Generated test cases', [
            'test_count' => count($testCases),
            'positive' => count($examples['pos']),
            'negative' => count($examples['neg']),
        ]);

        return ['test_cases' => $testCases];
    }
}
