<?php

declare(strict_types=1);

namespace Tests\Functional\Stix;

use Symfony\Bundle\FrameworkBundle\KernelBrowser;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

/**
 * Conversation STIX export hardening.
 *
 * Asserts that the conversation export bundle no longer contains the O(n^2)
 * `related-to` indicator-to-indicator full mesh, and that the semantically
 * meaningful relationships (`indicates`, `uses`) are preserved.
 *
 * The mesh was historically generated by the loop in
 * ConversationStixExportHandler::export() lines 68-86. It is deleted
 * because the conversation `report` object's `object_refs` already conveys
 * co-occurrence to OpenCTI without materialising O(n^2) arcs.
 */
final class ConversationStixExportHardeningTest extends WebTestCase
{
    private KernelBrowser $client;

    protected function setUp(): void
    {
        $this->client = static::createClient();
    }

    /**
     * Picks a conversation that has at least 3 IOCs (so the mesh would have
     * produced at least 3 related-to relationships if it were still generated).
     */
    private function getConvIdWithMultipleIocs(): string
    {
        $container = static::getContainer();
        /** @var \Doctrine\DBAL\Connection $conn */
        $conn = $container->get('doctrine.dbal.default_connection');

        $convId = $conn->fetchOne(
            'SELECT c.conv_id FROM conversation c'
            . ' JOIN message m ON c.conv_id = m.conv_id'
            . ' JOIN observed_ioc oi ON m.msg_id = oi.msg_id'
            . ' GROUP BY c.conv_id HAVING COUNT(DISTINCT oi.indicator_id) >= 3'
            . ' LIMIT 1',
        );

        if (!\is_string($convId) || $convId === '') {
            $this->markTestSkipped('No conversation with >=3 IOCs in test database');
        }

        return $convId;
    }

    /**
     * G8 multi-label: a conversation's secondary scam types must surface as
     * additional indicator `labels` in its STIX bundle, alongside the primary.
     */
    public function testIndicatorLabelsIncludeSecondaryScamTypes(): void
    {
        $convId = $this->getConvIdWithMultipleIocs();
        /** @var \Doctrine\DBAL\Connection $conn */
        $conn = static::getContainer()->get('doctrine.dbal.default_connection');
        $original = $conn->fetchOne('SELECT secondary_scam_types FROM conversation WHERE conv_id = ?', [$convId]);

        try {
            $conn->executeStatement(
                'UPDATE conversation SET secondary_scam_types = :sec::jsonb WHERE conv_id = :cid',
                ['sec' => json_encode([['code' => 'ROMANCE', 'confidence' => 0.55]]), 'cid' => $convId],
            );

            $this->client->request('GET', '/api/v1/conversations/' . $convId . '/export/stix', [], [], [
                'HTTP_AUTHORIZATION' => 'Bearer fake-jwt',
            ]);

            $this->assertResponseIsSuccessful();
            $data = json_decode((string) $this->client->getResponse()->getContent(), true);

            $indicatorLabels = [];

            foreach ($data['objects'] ?? [] as $obj) {
                if (\is_array($obj) && ($obj['type'] ?? '') === 'indicator' && \is_array($obj['labels'] ?? null)) {
                    $indicatorLabels = array_merge($indicatorLabels, $obj['labels']);
                }
            }

            self::assertContains('romance', $indicatorLabels, 'The secondary scam type must appear as an indicator label.');
        } finally {
            $conn->executeStatement(
                'UPDATE conversation SET secondary_scam_types = :sec WHERE conv_id = :cid',
                ['sec' => \is_string($original) ? $original : null, 'cid' => $convId],
            );
        }
    }

    /**
     * P0 acceptance: a regenerated conversation bundle must contain ZERO
     * `related-to` relationships whose source AND target are both indicators.
     */
    public function testNoRelatedToIndicatorIndicatorRelationships(): void
    {
        $convId = $this->getConvIdWithMultipleIocs();

        $this->client->request('GET', '/api/v1/conversations/' . $convId . '/export/stix', [], [], [
            'HTTP_AUTHORIZATION' => 'Bearer fake-jwt',
        ]);

        $this->assertResponseIsSuccessful();
        $data = $this->decodeResponse();

        $relatedToMesh = array_filter(
            $data['objects'],
            function (array $o): bool {
                if (($o['type'] ?? '') !== 'relationship') {
                    return false;
                }

                if (($o['relationship_type'] ?? '') !== 'related-to') {
                    return false;
                }

                $source = \is_string($o['source_ref'] ?? null) ? $o['source_ref'] : '';
                $target = \is_string($o['target_ref'] ?? null) ? $o['target_ref'] : '';

                return str_starts_with($source, 'indicator--') && str_starts_with($target, 'indicator--');
            },
        );

        $this->assertCount(
            0,
            $relatedToMesh,
            'Conversation export must not contain any related-to indicator-to-indicator relationships.',
        );
    }

    /**
     * Non-regression: dropping the related-to mesh must NOT affect the
     * `indicates` relationships, which carry the semantic link
     * indicator -> threat-actor and are critical for OpenCTI graph navigation.
     */
    public function testIndicatesRelationshipsPreservedInConversationExport(): void
    {
        $convId = $this->getConvIdWithMultipleIocs();

        $this->client->request('GET', '/api/v1/conversations/' . $convId . '/export/stix', [], [], [
            'HTTP_AUTHORIZATION' => 'Bearer fake-jwt',
        ]);

        $this->assertResponseIsSuccessful();
        $data = $this->decodeResponse();

        $indicatesRels = array_values(array_filter(
            $data['objects'],
            fn (array $o) => ($o['type'] ?? '') === 'relationship' && ($o['relationship_type'] ?? '') === 'indicates',
        ));

        $this->assertNotEmpty(
            $indicatesRels,
            'Conversation export must still contain indicates relationships after mesh removal (non-regression).',
        );

        foreach ($indicatesRels as $rel) {
            $source = \is_string($rel['source_ref'] ?? null) ? $rel['source_ref'] : '';
            $target = \is_string($rel['target_ref'] ?? null) ? $rel['target_ref'] : '';
            $this->assertStringStartsWith('indicator--', $source);
            $this->assertStringStartsWith('threat-actor--', $target);
        }
    }

    // ============================================================================
    // singleton conversation naming
    // ============================================================================
    //
    // The clustered conversation tests live in
    // ConversationStixExportClusterDelegationTest because they require
    // ClusteringFixtures setup. The singleton tests below run against the
    // standard test fixtures which contain unclustered conversations.

    /**
     * Picks any conversation with IOCs that does NOT belong to any cluster.
     */
    private function getSingletonConvId(): string
    {
        $container = static::getContainer();
        /** @var \Doctrine\DBAL\Connection $conn */
        $conn = $container->get('doctrine.dbal.default_connection');

        $convId = $conn->fetchOne(
            'SELECT c.conv_id FROM conversation c'
            . ' JOIN message m ON c.conv_id = m.conv_id'
            . ' JOIN observed_ioc oi ON m.msg_id = oi.msg_id'
            . ' WHERE NOT EXISTS ('
            . '   SELECT 1 FROM threat_actor_cluster_conversation tacc'
            . '   JOIN threat_actor_cluster tac ON tac.cluster_id = tacc.cluster_id'
            . '   WHERE tacc.conv_id = c.conv_id AND tac.merged_into_id IS NULL'
            . ' )'
            . ' GROUP BY c.conv_id LIMIT 1',
        );

        if (!\is_string($convId) || $convId === '') {
            $this->markTestSkipped('No singleton conversation with IOCs in test database');
        }

        return $convId;
    }

    public function testSingletonConversationUsesUnattributedNamingConvention(): void
    {
        $convId = $this->getSingletonConvId();

        $this->client->request('GET', '/api/v1/conversations/' . $convId . '/export/stix', [], [], [
            'HTTP_AUTHORIZATION' => 'Bearer fake-jwt',
        ]);

        $this->assertResponseIsSuccessful();
        $data = $this->decodeResponse();

        $actors = array_values(array_filter($data['objects'], fn (array $o) => ($o['type'] ?? '') === 'threat-actor'));
        $this->assertCount(1, $actors, 'Singleton conversation must contain exactly one threat-actor.');

        $name = \is_string($actors[0]['name'] ?? null) ? $actors[0]['name'] : '';
        $this->assertStringStartsWith(
            'Unattributed Scam Actor',
            $name,
            'Singleton conversation must use the new unattributed naming convention.',
        );
    }

    public function testSingletonConversationStillHasSingleThreatActor(): void
    {
        $convId = $this->getSingletonConvId();

        $this->client->request('GET', '/api/v1/conversations/' . $convId . '/export/stix', [], [], [
            'HTTP_AUTHORIZATION' => 'Bearer fake-jwt',
        ]);

        $data = $this->decodeResponse();
        $actors = array_filter($data['objects'], fn (array $o) => ($o['type'] ?? '') === 'threat-actor');

        $this->assertCount(1, $actors);
    }

    /**
     * @return array<string, mixed>
     */
    private function decodeResponse(): array
    {
        $content = (string) $this->client->getResponse()->getContent();
        $data = json_decode($content, true);
        $this->assertIsArray($data);
        $this->assertSame('bundle', $data['type'] ?? null);

        return $data;
    }

}
