<?php

declare(strict_types=1);

namespace Tests\Integration\Stix;

use Symfony\Bundle\FrameworkBundle\KernelBrowser;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

/**
 * Spec 060 Sprint 1 — conversation STIX export hardening.
 *
 * Asserts that the conversation export bundle no longer contains the O(n^2)
 * `related-to` indicator-to-indicator full mesh, and that the semantically
 * meaningful relationships (`indicates`, `uses`) are preserved.
 *
 * The mesh was historically generated by the loop in
 * ConversationStixExportHandler::export() lines 68-86. Spec 060 deletes it
 * because the conversation `report` object's `object_refs` already conveys
 * co-occurrence to OpenCTI without materialising O(n^2) arcs.
 */
final class ConversationStixExportHardeningTest extends WebTestCase
{
    private KernelBrowser $client;

    protected function setUp(): void
    {
        $this->client = static::createClient();
    }

    /**
     * Picks a conversation that has at least 3 IOCs (so the mesh would have
     * produced at least 3 related-to relationships if it were still generated).
     */
    private function getConvIdWithMultipleIocs(): string
    {
        $container = static::getContainer();
        /** @var \Doctrine\DBAL\Connection $conn */
        $conn = $container->get('doctrine.dbal.default_connection');

        $convId = $conn->fetchOne(
            'SELECT c.conv_id FROM conversation c'
            . ' JOIN message m ON c.conv_id = m.conv_id'
            . ' JOIN observed_ioc oi ON m.msg_id = oi.msg_id'
            . ' GROUP BY c.conv_id HAVING COUNT(DISTINCT oi.indicator_id) >= 3'
            . ' LIMIT 1',
        );

        if (!\is_string($convId) || $convId === '') {
            $this->markTestSkipped('No conversation with >=3 IOCs in test database');
        }

        return $convId;
    }

    /**
     * P0 acceptance: a regenerated conversation bundle must contain ZERO
     * `related-to` relationships whose source AND target are both indicators.
     */
    public function testNoRelatedToIndicatorIndicatorRelationships(): void
    {
        $convId = $this->getConvIdWithMultipleIocs();

        $this->client->request('GET', '/api/v1/conversations/' . $convId . '/export/stix', [], [], [
            'HTTP_AUTHORIZATION' => 'Bearer fake-jwt',
        ]);

        $this->assertResponseIsSuccessful();
        $data = $this->decodeResponse();

        $relatedToMesh = array_filter(
            $data['objects'],
            function (array $o): bool {
                if (($o['type'] ?? '') !== 'relationship') {
                    return false;
                }

                if (($o['relationship_type'] ?? '') !== 'related-to') {
                    return false;
                }

                $source = \is_string($o['source_ref'] ?? null) ? $o['source_ref'] : '';
                $target = \is_string($o['target_ref'] ?? null) ? $o['target_ref'] : '';

                return str_starts_with($source, 'indicator--') && str_starts_with($target, 'indicator--');
            },
        );

        $this->assertCount(
            0,
            $relatedToMesh,
            'Conversation export must not contain any related-to indicator-to-indicator relationships (spec 060 S1.1).',
        );
    }

    /**
     * Non-regression: dropping the related-to mesh must NOT affect the
     * `indicates` relationships, which carry the semantic link
     * indicator -> threat-actor and are critical for OpenCTI graph navigation.
     */
    public function testIndicatesRelationshipsPreservedInConversationExport(): void
    {
        $convId = $this->getConvIdWithMultipleIocs();

        $this->client->request('GET', '/api/v1/conversations/' . $convId . '/export/stix', [], [], [
            'HTTP_AUTHORIZATION' => 'Bearer fake-jwt',
        ]);

        $this->assertResponseIsSuccessful();
        $data = $this->decodeResponse();

        $indicatesRels = array_values(array_filter(
            $data['objects'],
            fn (array $o) => ($o['type'] ?? '') === 'relationship' && ($o['relationship_type'] ?? '') === 'indicates',
        ));

        $this->assertNotEmpty(
            $indicatesRels,
            'Conversation export must still contain indicates relationships after mesh removal (non-regression).',
        );

        foreach ($indicatesRels as $rel) {
            $source = \is_string($rel['source_ref'] ?? null) ? $rel['source_ref'] : '';
            $target = \is_string($rel['target_ref'] ?? null) ? $rel['target_ref'] : '';
            $this->assertStringStartsWith('indicator--', $source);
            $this->assertStringStartsWith('threat-actor--', $target);
        }
    }

    /**
     * @return array<string, mixed>
     */
    private function decodeResponse(): array
    {
        $content = (string) $this->client->getResponse()->getContent();
        $data = json_decode($content, true);
        $this->assertIsArray($data);
        $this->assertSame('bundle', $data['type'] ?? null);

        return $data;
    }
}
