nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization', 'X-CSRF-Token', 'X-Requested-With']
        expose_headers: ['X-Trace-Id', 'X-TAXII-Date-Added-First', 'X-TAXII-Date-Added-Last']
        max_age: 3600
    paths:
        '^/api/': ~
