<?php

declare(strict_types=1);

namespace App\Application\Scambaiting;

use Doctrine\DBAL\Connection;

/**
 * Spec 104 P3 — Read-only query for the Cognitive Mirror cache.
 *
 * Two access paths backing the panel:
 *   - getByPersona(): all scam types for a given persona
 *   - getByScamType(): all personas for a given scam type
 *
 * Both return the editorial framing fields + generation metadata
 * (model, date, prompt version) so the frontend can honestly stamp
 * each cell with "generated by X on Y".
 */
final readonly class PersonaMirrorQueryService
{
    public function __construct(
        private Connection $connection,
    ) {
    }

    /**
     * @return list<array{
     *   scam_type_code: string,
     *   scam_type_label: string,
     *   hunted_victim_profile: string,
     *   cognitive_lever: string,
     *   mirror_explanation: string,
     *   generated_at: string,
     *   generated_by_model: string,
     *   prompt_version: string,
     * }>
     */
    public function getByPersona(string $personaCode): array
    {
        $rows = $this->connection->fetchAllAssociative(
            'SELECT st.code AS scam_type_code,'
            . ' COALESCE(st.label, st.code) AS scam_type_label,'
            . ' psm.hunted_victim_profile, psm.cognitive_lever, psm.mirror_explanation,'
            . ' psm.generated_at, psm.generated_by_model, psm.prompt_version'
            . ' FROM persona_scam_mirror psm'
            . ' JOIN persona p ON p.persona_id = psm.persona_id'
            . ' JOIN lkp_scam_type st ON st.scam_type_id = psm.scam_type_id'
            . ' WHERE p.persona_code = :code AND p.is_active = TRUE AND st.active = TRUE'
            . ' ORDER BY st.code',
            ['code' => $personaCode]
        );

        return array_map($this->rowToArray(...), $rows);
    }

    /**
     * @return list<array{
     *   persona_code: string,
     *   persona_label: string,
     *   hunted_victim_profile: string,
     *   cognitive_lever: string,
     *   mirror_explanation: string,
     *   generated_at: string,
     *   generated_by_model: string,
     *   prompt_version: string,
     * }>
     */
    public function getByScamType(string $scamTypeCode): array
    {
        $rows = $this->connection->fetchAllAssociative(
            'SELECT p.persona_code,'
            . ' COALESCE(p.persona_label, p.persona_code) AS persona_label,'
            . ' psm.hunted_victim_profile, psm.cognitive_lever, psm.mirror_explanation,'
            . ' psm.generated_at, psm.generated_by_model, psm.prompt_version'
            . ' FROM persona_scam_mirror psm'
            . ' JOIN persona p ON p.persona_id = psm.persona_id'
            . ' JOIN lkp_scam_type st ON st.scam_type_id = psm.scam_type_id'
            . ' WHERE st.code = :code AND p.is_active = TRUE AND st.active = TRUE'
            . ' ORDER BY p.persona_code',
            ['code' => $scamTypeCode]
        );

        return array_map($this->rowToScamTypeArray(...), $rows);
    }

    /**
     * @param array<string, mixed> $row
     *
     * @return array{
     *   scam_type_code: string,
     *   scam_type_label: string,
     *   hunted_victim_profile: string,
     *   cognitive_lever: string,
     *   mirror_explanation: string,
     *   generated_at: string,
     *   generated_by_model: string,
     *   prompt_version: string,
     * }
     */
    private function rowToArray(array $row): array
    {
        return [
            'scam_type_code' => $this->str($row, 'scam_type_code'),
            'scam_type_label' => $this->str($row, 'scam_type_label'),
            'hunted_victim_profile' => $this->str($row, 'hunted_victim_profile'),
            'cognitive_lever' => $this->str($row, 'cognitive_lever'),
            'mirror_explanation' => $this->str($row, 'mirror_explanation'),
            'generated_at' => $this->str($row, 'generated_at'),
            'generated_by_model' => $this->str($row, 'generated_by_model'),
            'prompt_version' => $this->str($row, 'prompt_version'),
        ];
    }

    /**
     * @param array<string, mixed> $row
     *
     * @return array{
     *   persona_code: string,
     *   persona_label: string,
     *   hunted_victim_profile: string,
     *   cognitive_lever: string,
     *   mirror_explanation: string,
     *   generated_at: string,
     *   generated_by_model: string,
     *   prompt_version: string,
     * }
     */
    private function rowToScamTypeArray(array $row): array
    {
        return [
            'persona_code' => $this->str($row, 'persona_code'),
            'persona_label' => $this->str($row, 'persona_label'),
            'hunted_victim_profile' => $this->str($row, 'hunted_victim_profile'),
            'cognitive_lever' => $this->str($row, 'cognitive_lever'),
            'mirror_explanation' => $this->str($row, 'mirror_explanation'),
            'generated_at' => $this->str($row, 'generated_at'),
            'generated_by_model' => $this->str($row, 'generated_by_model'),
            'prompt_version' => $this->str($row, 'prompt_version'),
        ];
    }

    /** @param array<string, mixed> $row */
    private function str(array $row, string $key): string
    {
        return \is_string($row[$key] ?? null) ? $row[$key] : '';
    }
}
