<?php

declare(strict_types=1);

namespace App\Tests\Unit\Application\Stix;

use App\Application\Stix\ClusteredThreatActorStixBuilder;
use PHPUnit\Framework\TestCase;

/**
 * Unit tests for ClusteredThreatActorStixBuilder.
 *
 * Verifies STIX 2.1 compliance, correct extension, relationship types,
 * and auto-generated description.
 */
class ClusteredThreatActorStixBuilderTest extends TestCase
{
    private ClusteredThreatActorStixBuilder $builder;

    protected function setUp(): void
    {
        $this->builder = new ClusteredThreatActorStixBuilder();
    }

    private function sampleClusterData(): array
    {
        return [
            'cluster_id' => 'aaaaaaaa-bbbb-4000-8000-000000000001',
            'stix_id' => 'threat-actor--12345678-1234-5678-1234-567812345678',
            'name' => 'ScamBuster Cluster #A3F2 (14 conversations)',
            'status' => 'active',
            'conversation_count' => 14,
            'anchor_ioc_count' => 3,
            'sophistication' => 'intermediate',
            'primary_scam_types' => ['INVESTMENT', 'ADVANCE_FEE_419'],
            'goals' => ['financial-theft'],
            'first_seen' => '2026-02-06T00:00:00Z',
            'last_seen' => '2026-04-07T00:00:00Z',
            'algorithm_version' => '1.0',
            'anchor_ioc_types' => ['iban', 'wallet_btc'],
            'attck_techniques' => ['T1566'],
        ];
    }

    public function testBundleContainsThreatActor(): void
    {
        $bundle = $this->builder->buildBundle($this->sampleClusterData());

        $types = array_column($bundle, 'type');
        $this->assertContains('threat-actor', $types);
    }

    public function testThreatActorHasCorrectStixId(): void
    {
        $data = $this->sampleClusterData();
        $bundle = $this->builder->buildBundle($data);

        $actor = $this->findByType($bundle, 'threat-actor');
        $this->assertSame($data['stix_id'], $actor['id']);
    }

    public function testThreatActorSpecVersion21(): void
    {
        $bundle = $this->builder->buildBundle($this->sampleClusterData());

        $actor = $this->findByType($bundle, 'threat-actor');
        $this->assertSame('2.1', $actor['spec_version']);
    }

    public function testClusterTypeConsolidatedInExtension(): void
    {
        $bundle = $this->builder->buildBundle($this->sampleClusterData());

        $actor = $this->findByType($bundle, 'threat-actor');
        $ext = $actor['extensions']['x_scambuster_actor'] ?? [];

        $this->assertSame('consolidated', $ext['cluster_type']);
        $this->assertSame('2.0', $ext['schema_version']);
        $this->assertSame(14, $ext['conversation_count']);
        $this->assertSame(['iban', 'wallet_btc'], $ext['anchor_ioc_types']);
        $this->assertSame('realtime-anchor-ioc-clustering-v1.0', $ext['algorithm']);
    }

    public function testNoAttributedToRelationship(): void
    {
        $bundle = $this->builder->buildBundle($this->sampleClusterData());

        $relationships = array_filter($bundle, fn ($o) => ($o['type'] ?? '') === 'relationship');

        foreach ($relationships as $rel) {
            $this->assertNotSame('attributed-to', $rel['relationship_type'], 'No attributed-to relationships allowed');
        }
    }

    public function testIndicatorIndicatesThreatActorRelationships(): void
    {
        $data = $this->sampleClusterData();
        $data['indicator_stix_ids'] = ['indicator--aaa', 'indicator--bbb'];

        $bundle = $this->builder->buildBundle($data);

        $indicates = array_filter($bundle, fn ($o) => ($o['type'] ?? '') === 'relationship' && ($o['relationship_type'] ?? '') === 'indicates');

        $this->assertCount(2, $indicates, 'Should have 2 indicates relationships');

        foreach ($indicates as $rel) {
            $this->assertSame($data['stix_id'], $rel['target_ref']);
            $this->assertStringStartsWith('indicator--', $rel['source_ref']);
        }
    }

    public function testThreatActorUsesAttackPatternRelationship(): void
    {
        $bundle = $this->builder->buildBundle($this->sampleClusterData());

        $uses = array_filter($bundle, fn ($o) => ($o['type'] ?? '') === 'relationship' && ($o['relationship_type'] ?? '') === 'uses');

        $this->assertGreaterThan(0, \count($uses), 'Should have at least 1 uses relationship');

        foreach ($uses as $rel) {
            $this->assertStringStartsWith('threat-actor--', $rel['source_ref']);
            $this->assertStringStartsWith('attack-pattern--', $rel['target_ref']);
        }
    }

    public function testBundleContainsAttackPattern(): void
    {
        $bundle = $this->builder->buildBundle($this->sampleClusterData());

        $types = array_column($bundle, 'type');
        $this->assertContains('attack-pattern', $types);
    }

    public function testDescriptionAutoGenerated(): void
    {
        $bundle = $this->builder->buildBundle($this->sampleClusterData());

        $actor = $this->findByType($bundle, 'threat-actor');
        $desc = $actor['description'] ?? '';

        $this->assertStringContainsString('14 conversations', $desc);
        $this->assertStringContainsString('iban', $desc);
    }

    public function testThreatActorGoals(): void
    {
        $bundle = $this->builder->buildBundle($this->sampleClusterData());

        $actor = $this->findByType($bundle, 'threat-actor');
        $this->assertSame(['financial-theft'], $actor['goals']);
    }

    public function testThreatActorMotivation(): void
    {
        $bundle = $this->builder->buildBundle($this->sampleClusterData());

        $actor = $this->findByType($bundle, 'threat-actor');
        $this->assertSame('personal-gain', $actor['primary_motivation']);
        $this->assertSame(['criminal'], $actor['threat_actor_types']);
    }

    public function testFirstSeenLastSeen(): void
    {
        $bundle = $this->builder->buildBundle($this->sampleClusterData());

        $actor = $this->findByType($bundle, 'threat-actor');
        $this->assertArrayHasKey('first_seen', $actor);
        $this->assertArrayHasKey('last_seen', $actor);
    }

    public function testNoIndicatorStixIdsProducesNoIndicatesRelationships(): void
    {
        $data = $this->sampleClusterData();
        unset($data['indicator_stix_ids']);

        $bundle = $this->builder->buildBundle($data);

        $indicates = array_filter($bundle, fn ($o) => ($o['type'] ?? '') === 'relationship' && ($o['relationship_type'] ?? '') === 'indicates');
        $this->assertCount(0, $indicates);
    }

    public function testNoAttckTechniquesProducesNoAttackPattern(): void
    {
        $data = $this->sampleClusterData();
        $data['attck_techniques'] = [];

        $bundle = $this->builder->buildBundle($data);

        $aps = array_filter($bundle, fn ($o) => ($o['type'] ?? '') === 'attack-pattern');
        $this->assertCount(0, $aps);

        $uses = array_filter($bundle, fn ($o) => ($o['type'] ?? '') === 'relationship' && ($o['relationship_type'] ?? '') === 'uses');
        $this->assertCount(0, $uses);
    }

    /**
     * @return array<string, mixed>
     */
    private function findByType(array $bundle, string $type): array
    {
        foreach ($bundle as $obj) {
            if (($obj['type'] ?? '') === $type) {
                return $obj;
            }
        }

        $this->fail("No object of type '{$type}' found in bundle");
    }
}
